# Generated by Django 5.2.2 on 2025-06-15 20:09

import cloudinary.models
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Etiket Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
            ],
            options={
                'verbose_name': 'Blog Etiketi',
                'verbose_name_plural': 'Blog Etiketleri',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('working_hours', models.TextField(verbose_name='Çalışma Saatleri')),
                ('map_embed_url', models.TextField(verbose_name='Harita Embed URL')),
            ],
            options={
                'verbose_name': 'İletişim Bilgisi',
                'verbose_name_plural': 'İletişim Bilgileri',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=100, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu Mu?')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KVKKContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', tinymce.models.HTMLField(verbose_name='İçerik')),
            ],
            options={
                'verbose_name': 'KVKK İçeriği',
                'verbose_name_plural': 'KVKK İçeriği',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('icon', models.CharField(choices=[('fas fa-gavel', 'Ceza Hukuku'), ('fas fa-home', 'Gayrimenkul Hukuku'), ('fas fa-briefcase', 'İş Hukuku'), ('fas fa-users', 'Aile Hukuku'), ('fas fa-file-contract', 'Sözleşmeler'), ('fas fa-landmark', 'Ticaret Hukuku')], max_length=50, verbose_name='İkon')),
                ('excerpt', models.CharField(max_length=200, verbose_name='Kısa Açıklama')),
                ('description', tinymce.models.HTMLField(verbose_name='Kısa Açıklama')),
                ('detailed_content', tinymce.models.HTMLField(verbose_name='Detaylı İçerik')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kapak Görseli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', tinymce.models.HTMLField(verbose_name='İçerik')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Hizmet Süreci',
                'verbose_name_plural': 'Hizmet Süreci',
            },
        ),
        migrations.CreateModel(
            name='SiteOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyon/Ünvan')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profil Fotoğrafı')),
                ('short_bio', models.TextField(max_length=200, verbose_name='Kısa Bio')),
                ('bio', tinymce.models.HTMLField(verbose_name='Detaylı Bio')),
                ('quote', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Özlü Söz')),
                ('quote_author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Söz Sahibi')),
            ],
            options={
                'verbose_name': 'Site Sahibi',
                'verbose_name_plural': 'Site Sahibi',
            },
        ),
        migrations.CreateModel(
            name='TeamAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', tinymce.models.HTMLField(verbose_name='İçerik')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Ekip Hakkında',
                'verbose_name_plural': 'Ekip Hakkında',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyon')),
                ('expertise', models.CharField(max_length=200, verbose_name='Uzmanlık Alanı')),
                ('expertise_list', models.TextField(help_text='Virgülle ayırarak girin', verbose_name='Uzmanlık Listesi')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Fotoğraf')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Kapak Fotoğrafı')),
                ('bio', tinymce.models.HTMLField(verbose_name='Biyografi')),
                ('education', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Eğitim')),
                ('experience', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Deneyim')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Takım Üyesi',
                'verbose_name_plural': 'Takım Üyeleri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True, verbose_name='SEO URL')),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Kapak Görseli')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Detay Görseli')),
                ('summary', tinymce.models.HTMLField(verbose_name='Özet')),
                ('content', tinymce.models.HTMLField(verbose_name='İçerik')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında Mı?')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blogcategory', verbose_name='Kategori')),
                ('tags', models.ManyToManyField(blank=True, to='core.blogtag', verbose_name='Etiketler')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Onaylandı Mı?')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Yorumu',
                'verbose_name_plural': 'Blog Yorumları',
                'ordering': ['-created_at'],
            },
        ),
    ]
