# Generated by Django 5.2.2 on 2025-06-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(help_text='Bu alan otomatik olarak oluşturulacaktır', max_length=200, unique=True, verbose_name='SEO URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(help_text='Bu alan otomatik olarak oluşturulacaktır', unique=True, verbose_name='SEO URL'),
        ),
    ]
