# Generated by Django 5.2.2 on 2025-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_blogpost_slug_alter_teammember_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(blank=True, help_text='Bu alan otomatik olarak oluşturulacaktır', null=True, unique=True),
        ),
    ]
