# Generated by Django 5.2.2 on 2025-06-16 19:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_teammember_options_alter_teammember_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteowner',
            name='about_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Hakkımda Görseli'),
        ),
    ]
