# Generated by Django 5.2.2 on 2025-06-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
